### ISSUE TITLE
io.Reader

### ISSUE THREAD

**Issue by niaow** [davidsonff/qrand#3]
The go standard library uses io.Readers in order to get random data.
This would allow qrand to be used for various functions in go like ["crypto/rand".Prime](https://golang.org/pkg/crypto/rand/#Prime) which is used to generate random primes for generating asymmetric keys. This io.Reader should probably have a buffer to store random data. I can implement this later if you want.

["crypto/rand".Reader](https://golang.org/pkg/crypto/rand/#pkg-variables)

**Comment by davidsonff** [comment]
Yes. We just have to figure out how to implement one efficiently in Go and without making excessive requests to the server...

**Comment by davidsonff** [comment]
OK, check it out... Added a Reader... Think I got it right, but let me know! I'm didn't use a buffer because it didn't seem necessary?

**Comment by niaow** [comment]
Ok

**Comment by davidsonff** [comment]
Fixed!
